[[redirects]]
  from = "/"
  to = "/.netlify/functions/random-sim"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/websims/:splat"
  status = 200

[functions]
  directory = "functions" 